/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package janelas;

import controle.ControleConectaBanco;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author Petheus Rodrigues
 */
public class JanelaPrincipal extends javax.swing.JFrame {
    ControleConectaBanco controleConectaBanco;
    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        controleConectaBanco=new ControleConectaBanco();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPaneJanelaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuEdit = new javax.swing.JMenu();
        menuCadastrar = new javax.swing.JMenu();
        menuItemProduto = new javax.swing.JMenuItem();
        menuItemFornecedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout desktopPaneJanelaPrincipalLayout = new javax.swing.GroupLayout(desktopPaneJanelaPrincipal);
        desktopPaneJanelaPrincipal.setLayout(desktopPaneJanelaPrincipalLayout);
        desktopPaneJanelaPrincipalLayout.setHorizontalGroup(
            desktopPaneJanelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopPaneJanelaPrincipalLayout.setVerticalGroup(
            desktopPaneJanelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        menuEdit.setText("Edit");
        jMenuBar1.add(menuEdit);

        menuCadastrar.setText("Cadastrar");

        menuItemProduto.setText("Produto");
        menuItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProdutoActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemProduto);

        menuItemFornecedor.setText("Fornecedor");
        menuItemFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFornecedorActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemFornecedor);

        jMenuBar1.add(menuCadastrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPaneJanelaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPaneJanelaPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProdutoActionPerformed
        JanelaCadastroProduto janelaCadastroProduto=new JanelaCadastroProduto();
        desktopPaneJanelaPrincipal.add(janelaCadastroProduto);
        janelaCadastroProduto.setVisible(true);
    }//GEN-LAST:event_menuItemProdutoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        /*JanelaConectaBanco janelaConectaBanco = new JanelaConectaBanco();
        desktopPaneJanelaPrincipal.add(janelaConectaBanco);
        janelaConectaBanco.setVisible(true);
        menuCadastrar.setEnabled(false);*/
        boolean conectou = controleConectaBanco.abrirConexao("","","");
        JOptionPane.showMessageDialog(this, controleConectaBanco.getMensagem());
    }//GEN-LAST:event_formWindowOpened

    private void menuItemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFornecedorActionPerformed
        JanelaCadastroFornecedor janelaCadastroFornecedor=new JanelaCadastroFornecedor();
        desktopPaneJanelaPrincipal.add(janelaCadastroFornecedor);
        janelaCadastroFornecedor.setVisible(true);
    }//GEN-LAST:event_menuItemFornecedorActionPerformed
    public static JMenuItem getMenuCadastrar(){
        return menuCadastrar;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPaneJanelaPrincipal;
    private javax.swing.JMenuBar jMenuBar1;
    private static javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenuItem menuItemFornecedor;
    private javax.swing.JMenuItem menuItemProduto;
    // End of variables declaration//GEN-END:variables
}
