# Generated by Django 4.1.4 on 2022-12-24 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('classificacaoIndicativa', models.CharField(max_length=5, verbose_name='Classificação Indicativa')),
                ('ano', models.CharField(max_length=100, verbose_name='Ano')),
                ('diretor', models.CharField(max_length=100, verbose_name='Diretor')),
                ('duracao', models.CharField(max_length=100, verbose_name='Duração')),
                ('poster', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(max_length=30, verbose_name='Tipo de sala')),
                ('projecao', models.CharField(max_length=2, verbose_name='Projeção')),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('versao', models.CharField(max_length=20, verbose_name='Versão')),
                ('projecao', models.CharField(max_length=2, verbose_name='Projeção')),
                ('valor_inteira', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Inteira')),
                ('valor_meia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Meia')),
                ('encerrada', models.BooleanField(verbose_name='Encerrada')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.filme')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cliente')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.sessao')),
            ],
        ),
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.genero'),
        ),
    ]
