# Generated by Django 4.1.4 on 2022-12-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='poster',
            field=models.ImageField(upload_to='cinema\\cinema\\static\\img'),
        ),
    ]
