# Generated by Django 4.1.4 on 2022-12-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_filme_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='poster',
            field=models.FileField(upload_to='img/'),
        ),
    ]
