# Generated by Django 4.1.4 on 2022-12-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_filme_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='sinopse',
            field=models.CharField(default='', max_length=300, verbose_name='Sinopse'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='classificacaoIndicativa',
            field=models.IntegerField(verbose_name='Classificação Indicativa'),
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='tipo',
            field=models.CharField(choices=[(0, 'Inteira'), (0, 'Meia-entrada')], max_length=100, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='projecao',
            field=models.CharField(choices=[(0, '2D'), (1, '3D')], max_length=2, verbose_name='Projeção'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='encerrada',
            field=models.BooleanField(choices=[(0, 'Sim'), (1, 'Não')], verbose_name='Encerrada'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='projecao',
            field=models.CharField(choices=[(0, '2D'), (1, '3D')], max_length=2, verbose_name='Projeção'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='versao',
            field=models.CharField(choices=[(0, 'Dublado'), (1, 'Legendado')], max_length=20, verbose_name='Versão'),
        ),
    ]
