# Generated by Django 4.1.4 on 2022-12-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_filme_sinopse_alter_filme_classificacaoindicativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='sinopse',
            field=models.CharField(max_length=300, verbose_name='Sinopse'),
        ),
    ]
