# Generated by Django 4.1.4 on 2022-12-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_filme_sinopse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresso',
            name='tipo',
            field=models.CharField(choices=[('Inteira', 'Inteira'), ('Meia-entrada', 'Meia-entrada')], max_length=100, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='encerrada',
            field=models.BooleanField(choices=[('Sim', 'Sim'), ('Não', 'Não')], verbose_name='Encerrada'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='versao',
            field=models.CharField(choices=[('Dublado', 'Dublado'), ('Legendado', 'Legendado')], max_length=20, verbose_name='Versão'),
        ),
    ]
