# Generated by Django 4.1.4 on 2022-12-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_alter_sala_projecao_alter_sessao_projecao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='encerrada',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Encerrada'),
        ),
    ]
