# Generated by Django 4.1.4 on 2022-12-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_alter_sessao_encerrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresso',
            name='comprador',
        ),
    ]
