# Generated by Django 4.1.4 on 2022-12-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_remove_ingresso_comprador'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='codigo',
            field=models.CharField(default='', max_length=5, verbose_name='Codigo'),
        ),
    ]
