# Generated by Django 4.1.4 on 2022-12-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_sessao_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='codigo',
            field=models.CharField(max_length=5, verbose_name='Codigo'),
        ),
    ]
