# Generated by Django 4.1.4 on 2023-01-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_ingresso_comprador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='sinopse',
            field=models.TextField(verbose_name='Sinopse'),
        ),
    ]
