from django.urls import path
from .views import FilmeCreate, GeneroCreate, SessaoCreate,SalaCreate, IngressoCreate
from .views import FilmeUpdate, GeneroUpdate, SessaoUpdate, SalaUpdate,IngressoUpdate
from .views import FilmeDelete, GeneroDelete, SessaoDelete,SalaDelete, IngressoDelete
from .views import FilmeList, GeneroList, SessaoList,SalaList, IngressoList,Catalogo
from .views import FilmeListView,FilmeDetail,IngressoDetail,SessaoListCliente
""" from .views import CompraIngressoView """

urlpatterns = [
    path(
        'cadastrar/filme/',
        FilmeCreate.as_view(),
        name='cadastrar-filme'
    ),
    path(
        'cadastrar/genero/',
        GeneroCreate.as_view(),
        name='cadastrar-genero'
    ),
    path(
        'cadastrar/sessao/',
        SessaoCreate.as_view(),
        name='cadastrar-sessao'
    ),
    path(
        'cadastrar/sala/',
        SalaCreate.as_view(),
        name='cadastrar-sala'
    ),
    path(
        'cadastrar/ingresso/',
        IngressoCreate.as_view(),
        name='cadastrar-ingresso'
    ),
    path(
        'editar/filme/<int:pk>/',
        FilmeUpdate.as_view(),
        name='editar-filme'
    ),
    path(
        'editar/genero/<int:pk>/',
        GeneroUpdate.as_view(),
        name='editar-genero'
    ),
    path(
        'editar/sessao/<int:pk>/',
        SessaoUpdate.as_view(),
        name='editar-sessao'
    ),
    path(
        'editar/sala/<int:pk>/',
        SalaUpdate.as_view(),
        name='editar-sala'
    ),
    path(
        'editar/ingresso/<int:pk>/',
        IngressoUpdate.as_view(),
        name='editar-ingresso'
    ),
    path(
        'excluir/filme/<int:pk>/',
        FilmeDelete.as_view(),
        name='excluir-filme'
    ),
    path(
        'excluir/genero/<int:pk>/',
        GeneroDelete.as_view(),
        name='excluir-genero'
    ),
    path(
        'excluir/sessao/<int:pk>/',
        SessaoDelete.as_view(),
        name='excluir-sessao'
    ),
    path(
        'excluir/sala/<int:pk>/',
        SalaDelete.as_view(),
        name='excluir-sala'
    ),
    path(
        'excluir/ingresso/<int:pk>/',
        IngressoDelete.as_view(),
        name='excluir-ingresso'
    ),
    path(
        'listar/filme/',
        FilmeList.as_view(),
        name='listar-filme'
    ),
    path(
        'listar/objeto/',
        FilmeListView.as_view(),
        name='listar-objeto'
    ),
     path(
        'listar/genero/',
        GeneroList.as_view(),
        name='listar-genero'
    ),
     path(
        'listar/sessao/',
        SessaoList.as_view(),
        name='listar-sessao'
    ),
     path(
        'listar/sessao/cliente/',
        SessaoListCliente.as_view(),
        name='listar-sessao-cliente'
    ),
     path(
        'listar/sala/',
        SalaList.as_view(),
        name='listar-sala'
    ),
     path(
        'listar/ingresso/',
        IngressoList.as_view(),
        name='listar-ingresso'
    ),
     path(
        '',
        Catalogo.as_view(),
        name='catalogo'
    ),
     path(
        'detalhar/filme/<int:pk>/',
        FilmeDetail.as_view(),
        name='detalhar-filme'
    ),
     path(
        'detalhar/ingresso/<int:pk>/',
        IngressoDetail.as_view(),
        name='detalhar-ingresso'
    ),
]